# Generated by Django 4.1.6 on 2023-02-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plandetails',
            old_name='datails',
            new_name='details',
        ),
        migrations.AlterUniqueTogether(
            name='plandetails',
            unique_together={('plan', 'details')},
        ),
    ]
