# Generated by Django 4.1.6 on 2023-02-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0003_rename_details_plandetails_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='profile',
            new_name='profile_access',
        ),
    ]
