# Generated by Django 4.1.6 on 2023-02-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0004_rename_profile_subscription_profile_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='profile_access',
        ),
    ]
