# Generated by Django 4.1.6 on 2023-02-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0006_remove_subscription_plan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expire_hour',
            field=models.TimeField(),
        ),
    ]
